name: "IndexNow"
on:
  push:
    branches:
      - master       # 正确缩进：相对 branches: 缩进 2 空格
  schedule:
    - cron: '0 0,12 * * *'  # 注意这里要用半角单引号
jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: submit-to-bing
        uses: bojieyang/indexnow-action@v1
        with:
          sitemap-location: "https://www.tdacg.com/sitemap.xml"  # change it
          endpoint: "www.bing.com"
          limit: 150
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: ${{ secrets.INDEXNOW_KEY_LOCATION }}
